### ISSUE TITLE
希望可以自动选择更新版的 kernel

### ISSUE THREAD

**Issue by cyrilkong** [chiakge/Linux-NetSpeed#1]
建议可以判定是 4.9 的内核以后的更新版都可以支持，然后让用户自己选择 header 版本

**Comment by nanqinlang** [comment]
不要想太多，headers 不是给你随便选的，版本必须一致。

而且，不要闲的没事去追 mainline，自作聪明等于作死。

然后，问我为什么这么说？因为我是作者。
