### ISSUE TITLE
一直显示：未安装加速模块

### ISSUE THREAD

**Issue by iweixubin** [chiakge/Linux-NetSpeed#15]
系统：Ubuntu 16.04 i386
运行
wget -N --no-check-certificate "https://raw.githubusercontent.com/chiakge/Linux-NetSpeed/master/tcp.sh" && chmod +x tcp.sh && ./tcp.sh
显示
当前状态: 已安装 Lotserver 加速内核 , 未安装加速模块

选择：8. 使用Lotserver(锐速)加速

然后
当前状态: 已安装 Lotserver 加速内核 , 未安装加速模块

是不是说明不成功？？？

**Comment by diyes** [comment]
跟你一样 我的是Debian 9

**Comment by iweixubin** [comment]
不知道本项目为什么会出现在我的仓库中，可以移除么？

**Comment by 1211030769** [comment]
俺也一样
