### ISSUE TITLE
这个脚本有问题，大家千万别用，会把内核删掉的！！！

### ISSUE THREAD

**Issue by huangguiniab** [chiakge/Linux-NetSpeed#50]
成功干废了我的vps，大把数据付之东流，只能怪自己倒霉了，内核都没了救援模式都进不去
![Screenshot_20200926-024027](https://user-images.githubusercontent.com/47934913/94304436-26440c00-ffa2-11ea-930b-8032a15b9215.jpg)

**Comment by bunsl** [comment]
我也是！

**Comment by po888375** [comment]
……出现蓝色界面的时候选择no啊

**Comment by huangguiniab** [comment]
> ……出现蓝色界面的时候选择no啊

啥界面都没有，重启也啥界面没有，运行完脚本就啥事都没发生，直到服务器计划任务自动重启服务器的时候就成这逼样。我再重启用grub命令行一看，好家伙，vmliugz和initrd被删除了，内核都没了，能启动就怪了，我去问vultr客服能不能补上文件或者挂载dvd进救援模式，他们告诉我不可以，只能回滚早期快照。我心都碎了，这台服务器上有我和我朋友日日夜夜奋斗的游戏存档，结果我一个命令就拿不出来了，你懂我有多绝望吗？我他妈的没备份没快照，现在老实了，定期备份，绝对不搞bbr，bbrplus之类涉及内核的操作，我强烈建议你也别搞，这是我一辈子的心理阴影。

**Comment by po888375** [comment]
> > ……出现蓝色界面的时候选择no啊
> 
> 啥界面都没有，重启也啥界面没有，运行完脚本就啥事都没发生，直到服务器计划任务自动重启服务器的时候就成这逼样。我再重启用grub命令行一看，好家伙，vmliugz和initrd被删除了，内核都没了，能启动就怪了，我去问vultr客服能不能补上文件或者挂载dvd进救援模式，他们告诉我不可以，只能回滚早期快照。我心都碎了，这台服务器上有我和我朋友日日夜夜奋斗的游戏存档，结果我一个命令就拿不出来了，你懂我有多绝望吗？我他妈的没备份没快照，现在老实了，定期备份，绝对不搞bbr，bbrplus之类涉及内核的操作，我强烈建议你也别搞，这是我一辈子的心理阴影。

我用我的腾讯云轻量刚刚安装了下，也把我内核删了。。不过我没啥资料，重装下系统又好了。

**Comment by huangguiniab** [comment]
> > > ……出现蓝色界面的时候选择no啊
> > 
> > 啥界面都没有，重启也啥界面没有，运行完脚本就啥事都没发生，直到服务器计划任务自动重启服务器的时候就成这逼样。我再重启用grub命令行一看，好家伙，vmliugz和initrd被删除了，内核都没了，能启动就怪了，我去问vultr客服能不能补上文件或者挂载dvd进救援模式，他们告诉我不可以，只能回滚早期快照。我心都碎了，这台服务器上有我和我朋友日日夜夜奋斗的游戏存档，结果我一个命令就拿不出来了，你懂我有多绝望吗？我他妈的没备份没快照，现在老实了，定期备份，绝对不搞bbr，bbrplus之类涉及内核的操作，我强烈建议你也别搞，这是我一辈子的心理阴影。
> 
> 我用我的腾讯云轻量刚刚安装了下，也把我内核删了。。不过我没啥资料，重装下系统又好了。

看到#52了，和腾讯轻量云没啥关系，好像和系统与人品有关，centos系的大概率装不上，有几率重启再也不开机，但是ubuntu倒是没这个问题(｡•́︿•̀｡)，我觉得可能是我人品不行

**Comment by po888375** [comment]
> > > > ……出现蓝色界面的时候选择no啊
> > > 
> > > 
> > > 啥界面都没有，重启也啥界面没有，运行完脚本就啥事都没发生，直到服务器计划任务自动重启服务器的时候就成这逼样。我再重启用grub命令行一看，好家伙，vmliugz和initrd被删除了，内核都没了，能启动就怪了，我去问vultr客服能不能补上文件或者挂载dvd进救援模式，他们告诉我不可以，只能回滚早期快照。我心都碎了，这台服务器上有我和我朋友日日夜夜奋斗的游戏存档，结果我一个命令就拿不出来了，你懂我有多绝望吗？我他妈的没备份没快照，现在老实了，定期备份，绝对不搞bbr，bbrplus之类涉及内核的操作，我强烈建议你也别搞，这是我一辈子的心理阴影。
> > 
> > 
> > 我用我的腾讯云轻量刚刚安装了下，也把我内核删了。。不过我没啥资料，重装下系统又好了。
> 
> 看到#52了，和腾讯轻量云没啥关系，好像和系统与人品有关，centos系的大概率装不上，有几率重启再也不开机，但是ubuntu倒是没这个问题(｡•́︿•̀｡)，我觉得可能是我人品不行

我都是用debian装的，就轻量出过问题，其他从没问题。centos我就没装成功过，哈哈

**Comment by Patrick-Ren** [comment]
vultr 有免费的 snapshot，定时备份一下。我安装完发现一个 node 进程被干掉了，后来手动重启了。不过重要的 VPS 还是不要运行未经验证的脚本了

**Comment by SekiBetu** [comment]
https://github.com/ylx2016/Linux-NetSpeed 可以考虑使用这个魔改版，亲测腾讯轻量香港云成功替换内核

**Comment by huangguiniab** [comment]
唉，累了一个人哭会吧，朋友和我绝交了，以后不整这种东西了
